// Create an array of food items
const foodItems = [
    {
      name: 'Burger',
      id: 1,
      description: 'Delicious beef burger with lettuce and cheese',
      rating: 4.5,
      price: 8.99,
      offer: '20% off',
      category: 'non-veg',
      cuisines: ['American'],
      image: 'https://media.istockphoto.com/id/1206323282/photo/juicy-hamburger-on-white-background.jpg?s=612x612&w=0&k=20&c=K0DxyiChLwewXcCy8aLjjOqkc8QXPgQMAW-vwRCzqG4=',
    },
    {
      name: 'Pizza',
      id: 2,
      description: 'Freshly baked pizza with a variety of toppings',
      rating: 4.2,
      price: 12.99,
      offer: 'Free garlic bread',
      category: 'non-veg',
      cuisines: ['Italian'],
      image: 'https://media.istockphoto.com/id/938742222/photo/cheesy-pepperoni-pizza.jpg?s=612x612&w=0&k=20&c=D1z4xPCs-qQIZyUqRcHrnsJSJy_YbUD9udOrXpilNpI=',
    },
    {
      name: 'Sushi',
      id: 3,
      description: 'Assorted sushi rolls with soy sauce and wasabi',
      rating: 4.7,
      price: 15.99,
      offer: '',
      category: 'non-veg',
      cuisines: ['Japanese'],
      image: 'https://st4.depositphotos.com/19157714/31390/i/450/depositphotos_313903296-stock-photo-close-view-delicious-sushi-set.jpg',
    },
    {
      name: 'Pasta',
      id: 4,

      description: 'Creamy pasta with choice of Alfredo or Marinara sauce',
      rating: 4.0,
      price: 9.99,
      offer: 'Buy 1 get 1 free',
      category: 'veg',
      cuisines: ['Italian'],
      image: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=1600',
    },
    {
      name: 'Tacos',
      id: 5,
      description: 'Flavorful tacos with seasoned meat and toppings',
      rating: 4.3,
      price: 7.99,
      offer: 'Combo deal available',
      category: 'non-veg',
      cuisines: ['Mexican'],
      image: 'https://media.istockphoto.com/id/614313140/photo/soft-beef-tacos-with-fries.jpg?s=612x612&w=0&k=20&c=KxBKdcWFKWCQwLWiil-Rgvlpl9l8SZXwkvjnCiWcia8=',
    },
    {
      name: 'Samosa',
      id: 6,

      description: 'Crispy fried pastry with spicy potato filling',
      rating: 4.6,
      price: 1.99,
      offer: '',
      category: 'veg',
      cuisines: ['Indian'],
      image: 'https://images.pexels.com/photos/14477873/pexels-photo-14477873.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      name: 'Sushi Bowl',
      id: 7,

      description: 'A bowl of sushi rice topped with fresh seafood and vegetables',
      rating: 4.8,
      price: 13.99,
      offer: '10% off for first-time orders',
      category: 'non-veg',
      cuisines: ['Japanese', 'Asian'],
      image: 'https://media.istockphoto.com/id/1072044110/photo/poke-bowl-with-salmon-served-in-bowl.jpg?s=612x612&w=0&k=20&c=FZvPd0m6LLQUgmh5mo2EtRDMJGTDsbQTpc2ZYAlQeC8=',
    },
    {
      name: 'Sandwich',
      id: 8,

      description: 'Classic sandwich with a variety of fillings',
      rating: 4.4,
      price: 6.99,
      offer: 'Add-ons available',
      category: 'veg',
      cuisines: ['International'],
      image: 'https://media.istockphoto.com/id/1256670482/photo/turkey-sandwich-with-tomato-and-lettuce.jpg?s=612x612&w=0&k=20&c=CPwIFBHQqOob3SNZbegKKjUVL6xkUZgoQ2cxT0jcUrQ=',
    },
    {
      name: 'Chicken Wings',
      id: 9,

      description: 'Crispy chicken wings with choice of sauces',
      rating: 4.2,
      price: 10.99,
      offer: 'Family pack available',
      category: 'non-veg',
      cuisines: ['American'],
      image: 'https://media.istockphoto.com/id/835903320/photo/baked-chicken-wings-with-sesame-seeds-and-sweet-chili-sauce-on-white-wooden-board.jpg?s=612x612&w=0&k=20&c=SH8ZCkEKuWD_wxulpntIJ0uD4yRnUf9UXovQwSwrmmA=',
    },
    {
      name: 'Paneer Tikka',
      id: 10,

      description: 'Grilled paneer cubes marinated in Indian spices',
      rating: 4.7,
      price: 8.99,
      offer: 'Special combo offer',
      category: 'veg',
      cuisines: ['Indian'],
      image: 'https://media.istockphoto.com/id/1186759790/photo/paneer-tikka-at-skewers-in-black-bowl-at-dark-slate-background-paneer-tikka-is-an-indian.jpg?s=612x612&w=0&k=20&c=cITToqM1KEnrixXjoLhEciqP24SxdKtW3QXykq-W5OE=',
    },
    // Add more food items here
  ];
  
 export default foodItems;